/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-secondary-fixed": "#2f1500",
          "surface-dim": "#d9dadc",
          "on-secondary-fixed-variant": "#6f3900",
          "stadium-blue": "#0052CC",
          "tertiary-fixed": "#8df7c1",
          "tertiary-fixed-dim": "#71dba6",
          "surface-container-high": "#e7e8ea",
          "tertiary": "#004e32",
          "surface-container-highest": "#e1e2e4",
          "secondary-fixed-dim": "#ffb77f",
          "secondary-container": "#ff8a00",
          "surface-variant": "#e1e2e4",
          "secondary": "#914c00",
          "primary-container": "#0052cc",
          "on-surface": "#191c1e",
          "alert-orange": "#FF8A00",
          "outline": "#737685",
          "outline-variant": "#c3c6d6",
          "on-secondary-container": "#613100",
          "on-tertiary-fixed": "#002113",
          "on-error-container": "#93000a",
          "error-container": "#ffdad6",
          "background": "#f8f9fb",
          "surface-dark": "#172B4D",
          "on-tertiary-fixed-variant": "#005235",
          "pitch-green": "#00875A",
          "on-primary-fixed-variant": "#0040a2",
          "inverse-primary": "#b2c5ff",
          "surface-container-lowest": "#ffffff",
          "on-primary-container": "#c4d2ff",
          "on-tertiary-container": "#7de7b2",
          "error": "#ba1a1a",
          "surface-container-low": "#f3f4f6",
          "tertiary-container": "#006844",
          "inverse-on-surface": "#f0f1f3",
          "surface-container": "#edeef0",
          "on-tertiary": "#ffffff",
          "secondary-fixed": "#ffdcc4",
          "info-blue": "#0747A6",
          "on-secondary": "#ffffff",
          "on-surface-variant": "#434654",
          "sensory-calm": "#EAE6FF",
          "primary-fixed-dim": "#b2c5ff",
          "on-primary": "#ffffff",
          "primary": "#003d9b",
          "on-primary-fixed": "#001848",
          "surface": "#f8f9fb",
          "on-error": "#ffffff",
          "surface-tint": "#0c56d0",
          "surface-bright": "#f8f9fb",
          "on-background": "#191c1e",
          "primary-fixed": "#dae2ff",
          "critical-red": "#DE350B",
          "inverse-surface": "#2e3132"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "margin-mobile": "16px",
          "container-max-width": "1280px",
          "margin-desktop": "32px",
          "gutter": "16px",
          "unit": "4px"
      },
      "fontFamily": {
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "label-caps": ["JetBrains Mono", "monospace"],
          "body-md": ["Inter", "sans-serif"],
          "status-indicator": ["JetBrains Mono", "monospace"],
          "headline-xl": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "status-indicator": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
          "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
